services:
  consul-server:
    image: ghcr.io/sentiric/sentiric-discovery:latest
    container_name: consul-server
    restart: always
    network_mode: "host"
    volumes:
      - consul_data:/consul/data
      - ./consul-config:/consul/config
    command: >
      agent -server -bootstrap-expect=3 -ui
      -node=${CURRENT_NODE_NAME}
      -client=0.0.0.0
      -bind=${CURRENT_NODE_IP}
      -advertise=${CURRENT_NODE_IP}
      -retry-join="${NODE_B_IP}"
      -retry-join="${NODE_C_IP}"
      -config-dir=/consul/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8500/v1/agent/self"]
      interval: 10s
      timeout: 5s
      retries: 5

  sip-gateway:
    build:
      context: ../services/sip-gateway
    container_name: sip-gateway
    restart: always
    network_mode: "host"
    depends_on:
      consul-server:
        condition: service_healthy

volumes:
  consul_data:
    name: "sentiric_consul_data"